/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import info5100.university.example.University;
import javax.swing.ImageIcon;

/**
 *
 * @author harshikag
 */
public class AdminLogin extends javax.swing.JPanel {

    University uni = new University();
    ImageIcon contact = new ImageIcon("contacts-24.png");
    ImageIcon passwordicon = new ImageIcon("lock-24.png");
    LoginForm login;

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin(LoginForm lg) {
        System.out.println("inside login");
        initComponents();
        login = lg;
        jLabel_user.setIcon(contact);
        jLabel_pass.setIcon(passwordicon);
        uni.setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameText = new javax.swing.JTextField();
        jButton_login = new javax.swing.JButton();
        jLabel_user = new javax.swing.JLabel();
        PasswordText = new javax.swing.JPasswordField();
        jLabel_pass = new javax.swing.JLabel();

        jButton_login.setBackground(new java.awt.Color(42, 187, 155));
        jButton_login.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login.setText("Login");
        jButton_login.setOpaque(true);
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jLabel_user.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        PasswordText.setText("jPasswordField1");

        jLabel_pass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_user, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_pass, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PasswordText, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(usernameText))))
                    .addContainerGap(99, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_user))
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_pass))
                    .addGap(51, 51, 51)
                    .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
        char[] ch = PasswordText.getPassword();
        String pwd = new String(ch);

        for (int j = 0; j < uni.getAdminList().size(); j++) {
            if (uni.getAdminList().get(j).getUsername().equalsIgnoreCase(usernameText.getText())
                    && uni.getAdminList().get(j).getPassword().equalsIgnoreCase(pwd)) {
                AdminDashboard admin = new AdminDashboard(uni, uni.getAdminList().get(j));
                login.dispose();
                admin.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel_pass;
    private javax.swing.JLabel jLabel_user;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
