/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import info5100.university.example.Employer.EmployerDirectory;
import java.awt.Color;
import java.util.regex.Matcher;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshikag
 */
public class EmployerDetails extends javax.swing.JPanel {

    ImageIcon northeasternLogo = new ImageIcon("husky.png");
    EmployerDirectory employerDirectory;
    DefaultTableModel model;

    /**
     * Creates new form EmployerDetails
     */
    public EmployerDetails() {
        initComponents();
        jLabel6.setIcon(northeasternLogo);
        Border blackline = BorderFactory.createLineBorder(Color.black);
        jPanel1.setBorder(blackline);
        model = new DefaultTableModel();
        employer_table.setModel(model);
        model.addColumn("Name");
        model.addColumn("Contact");
        model.addColumn("Established Since");
        model.addColumn("Address");
        model.addColumn("Association with University");
        System.out.println("constructor....");
        employerDirectory = new EmployerDirectory();
        employerDirectory.newEmployer("Amazon", "Boston", "123-456-7890", 5, 3);
        employerDirectory.newEmployer("Google", "California", "123-456-7890", 10, 5);
        employerDirectory.newEmployer("facebook", "NewYork", "123-456-7890", 15, 13);
        employerDirectory.newEmployer("Tesla", "Boston", "123-456-7890", 20, 2);
        employerDirectory.newEmployer("ABC", "Boston", "123-456-7890", 20, 2);
        employerDirectory.newEmployer("DEF", "Boston", "123-456-7890", 20, 2);
        employerDirectory.newEmployer("Tesla", "Boston", "123-456-7890", 20, 2);
        employerDirectory.newEmployer("TesHJIla", "Boston", "123-456-7890", 20, 2);
        employerDirectory.newEmployer("kdjhwesfh", "Boston", "123-456-7890", 20, 2);

        Color ivory = new Color(255, 255, 208);
        employer_table.setOpaque(false);
        employer_table.setBackground(ivory);
        viewEmployer();

    }

    public void viewEmployer() {
        if (employerDirectory.getEmployerlist().size() > 0) {
            for (int i = 0; i < employerDirectory.getEmployerlist().size(); i++) {

                model.addRow(new Object[]{
                    employerDirectory.getEmployerlist().get(i).getName(),
                    employerDirectory.getEmployerlist().get(i).getContactNo(),
                    employerDirectory.getEmployerlist().get(i).getCompanyAge(),
                    employerDirectory.getEmployerlist().get(i).getLocation(),
                    employerDirectory.getEmployerlist().get(i).getCompanyAssociationWithUniversity()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EmployerNameLabel = new javax.swing.JLabel();
        CompanyNameTextField = new javax.swing.JTextField();
        ContactLabel = new javax.swing.JLabel();
        ContactText = new javax.swing.JTextField();
        AssociationAgeLabel = new javax.swing.JLabel();
        AssociationAgeText = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        RevenueTitle = new javax.swing.JLabel();
        deleteNameLabel = new javax.swing.JLabel();
        deleteEmpNameText = new javax.swing.JTextField();
        RevenueTitle1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        employer_table = new javax.swing.JTable();
        RevenueTitle2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setText("jLabel6");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STUDENT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        EmployerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EmployerNameLabel.setText("Employer Name");

        CompanyNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ContactLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ContactLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ContactLabel.setText("Contact No");

        ContactText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        AssociationAgeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AssociationAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AssociationAgeLabel.setText("Associated with university");

        AssociationAgeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ageLabel.setText("Established since (in years)");

        ageText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressLabel.setText("Address");

        addButton.setBackground(new java.awt.Color(0, 0, 0));
        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Employer");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(0, 0, 0));
        DeleteButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete Employer");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        addressText.setColumns(20);
        addressText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressText.setRows(5);
        jScrollPane1.setViewportView(addressText);

        RevenueTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RevenueTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RevenueTitle.setText("Delete an employer");

        deleteNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deleteNameLabel.setText("Enter Employer Name");

        deleteEmpNameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteEmpNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmpNameTextActionPerformed(evt);
            }
        });

        RevenueTitle1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RevenueTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RevenueTitle1.setText("View employers");

        employer_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        employer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(employer_table);

        RevenueTitle2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RevenueTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RevenueTitle2.setText("Add an employer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContactLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContactText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CompanyNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(321, 321, 321))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(deleteNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteEmpNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(AssociationAgeLabel)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ageText)
                                    .addComponent(AssociationAgeText)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(addButton))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ageLabel)
                                .addGap(321, 321, 321))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(RevenueTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RevenueTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(RevenueTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(DeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RevenueTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmployerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AssociationAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssociationAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RevenueTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RevenueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteNameLabel)
                    .addComponent(deleteEmpNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DeleteButton)
                .addContainerGap(411, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
//        employerDirectory = new EmployerDirectory();

        boolean flag = false;
        
        if(CompanyNameTextField.getText().isEmpty() || AssociationAgeText.getText().isEmpty() || ContactText.getText().isEmpty()
                || ageText.getText().isEmpty() || addressText.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, "Please enter all fields");
        }
        
        String pattern = "^[A-Za-z]+$";
        String number = "^\\d+$";
        java.util.regex.Pattern r = java.util.regex.Pattern.compile(pattern);
        java.util.regex.Pattern r1 = java.util.regex.Pattern.compile(number);
        Matcher m = r.matcher(CompanyNameTextField.getText());
        Matcher m1 = r1.matcher(AssociationAgeText.getText());
        Matcher m2 = r1.matcher(ContactText.getText());
        Matcher m3 = r1.matcher(ageText.getText());
        if (((!m.find()) ||  (!m1.find()) ||  (!m2.find()) || (!m3.find()) ) && 
            (!CompanyNameTextField.getText().isEmpty() && (!AssociationAgeText.getText().isEmpty()) && (!ContactText.getText().isEmpty())
                && (!ageText.getText().isEmpty()) && (!addressText.getText().isEmpty()))) {
            flag = true;
            JOptionPane.showMessageDialog(null, "Please enter Valid data");
        }
        
        if(flag == false){
        employerDirectory.newEmployer(CompanyNameTextField.getText(), addressText.getText(), ContactText.getText(), Integer.parseInt(ageText.getText()), Integer.parseInt(AssociationAgeText.getText()));
//        viewEmployer();
        System.out.println("details " + employerDirectory.getEmployerlist().get(0).getName());
        JOptionPane.showMessageDialog(this, "Employer Details added successfully");
        model.addRow(new Object[]{
            CompanyNameTextField.getText(),
            ContactText.getText(),
            ageText.getText(),
            AssociationAgeText.getText(),
            addressText.getText()
        });
        
            CompanyNameTextField.setText("");
            ContactText.setText("");
            ageText.setText("");
            AssociationAgeText.setText("");
            addressText.setText("");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
//        employerDirectory = new EmployerDirectory();

        boolean flag = false;
        
        if(deleteEmpNameText.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter name to delete");
            flag = true;
        }
        
        if(flag == false){
        Boolean isDelete = employerDirectory.deleteEmployer(deleteEmpNameText.getText());
        for (int i = 0; i < employer_table.getRowCount(); i++) {
            System.out.println((String) employer_table.getValueAt(i, 0) + " sajdhfedhfd " + deleteEmpNameText.getText());
            if (((String) employer_table.getValueAt(i, 0)).equals(deleteEmpNameText.getText())) {
                System.out.println("inside " + i);
                model.removeRow(i);

            }//end of if block
        }
        if (isDelete){
            JOptionPane.showMessageDialog(this, "Employer Details deleted successfully");
        }
        }
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void deleteEmpNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmpNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEmpNameTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AssociationAgeLabel;
    private javax.swing.JTextField AssociationAgeText;
    private javax.swing.JTextField CompanyNameTextField;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JTextField ContactText;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel EmployerNameLabel;
    private javax.swing.JLabel RevenueTitle;
    private javax.swing.JLabel RevenueTitle1;
    private javax.swing.JLabel RevenueTitle2;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextArea addressText;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageText;
    private javax.swing.JTextField deleteEmpNameText;
    private javax.swing.JLabel deleteNameLabel;
    private javax.swing.JTable employer_table;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
