/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import info5100.university.example.Department.Department;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author harshikag
 */
public class Revenue extends javax.swing.JPanel {
    ImageIcon northeasternLogo = new ImageIcon("husky.png");
    int Revenue;    
    int RevenueYear;
    int LossYear;
    String[] semesterList;

    int Loss;
    Department department;
    /**
     * Creates new form Revenue
     */
    public Revenue(Department department, String[] semesterList) {
        initComponents();
        semesterList = semesterList;
        department = department;
        headerLogo.setIcon(northeasternLogo);
        Border blackline = BorderFactory.createLineBorder(Color.black);
        jPanel1.setBorder(blackline);
        int profit = department.calculateRevenuesBySemester("Fall2020");        
        int loss = department.calculateLossBySemester("Fall2020");
        Revenue = profit;
        double pp;
        double ll;
        double totalProfit = 0;        
        double totalLoss = 0;
        System.out.println(profit + " profit" + loss + " loss");
        Loss = loss;
        for(int i = 0; i < semesterList.length; i ++) {
            System.out.println(semesterList[i] + " semester profit " + department.calculateRevenuesBySemester(semesterList[i]));
            pp = department.calculateRevenuesBySemester(semesterList[i]);
            totalProfit += pp;
            ll = department.calculateLossBySemester(semesterList[i]);
            totalLoss += ll;
        }
        RevenueSemLabel.setText(String.valueOf("Fall2020 Revenue: " +Revenue));
        lossSemLabel.setText(String.valueOf("Fall2020 Loss: " + Loss));        
        LossYearLabel.setText(String.valueOf("Year Loss: " + totalLoss));
        revenueYearLabel.setText(String.valueOf("Fall2020 Loss: " + totalProfit));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RevenueSemLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        headerLogo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RevenueTitle = new javax.swing.JLabel();
        LossYearLabel = new javax.swing.JLabel();
        LossTitle = new javax.swing.JLabel();
        revenueYearLabel = new javax.swing.JLabel();
        LossTitle1 = new javax.swing.JLabel();
        RevenueSemLabel = new javax.swing.JLabel();
        LossTitle2 = new javax.swing.JLabel();
        lossSemLabel = new javax.swing.JLabel();

        RevenueSemLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        headerLogo.setText("jLabel6");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STUDENT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(474, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        RevenueTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RevenueTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RevenueTitle.setText("Revenue of university based on courses taken");

        LossYearLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        LossTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LossTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LossTitle.setText("Loss by university based on courses taken");

        revenueYearLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        LossTitle1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LossTitle1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LossTitle1.setText("Revenue of university based on courses taken in a year");

        RevenueSemLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        LossTitle2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LossTitle2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LossTitle2.setText("Loss by university based on courses taken in a year");

        lossSemLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(RevenueSemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(revenueYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(LossYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LossTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RevenueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LossTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LossTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lossSemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(RevenueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RevenueSemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LossTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lossSemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(LossTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revenueYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LossTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LossYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LossTitle;
    private javax.swing.JLabel LossTitle1;
    private javax.swing.JLabel LossTitle2;
    private javax.swing.JLabel LossYearLabel;
    private javax.swing.JLabel RevenueSemLabel;
    private javax.swing.JLabel RevenueSemLabel1;
    private javax.swing.JLabel RevenueTitle;
    private javax.swing.JLabel headerLogo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lossSemLabel;
    private javax.swing.JLabel revenueYearLabel;
    // End of variables declaration//GEN-END:variables
}
