/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.University;
import java.awt.Color;
import java.util.regex.Matcher;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshikag
 */
public class StudentHome extends javax.swing.JPanel {
    ImageIcon northeasternLogo = new ImageIcon("husky.png");
    PersonDirectory personDirectory;
    StudentDirectory studentDirectory;
    University uni;
    StudentProfile student;

    /**
     * Creates new form StudentHome
     */
    public StudentHome(University university, StudentProfile stud) {
        initComponents();
        jLabel6.setIcon(northeasternLogo);
        Border blackline = BorderFactory.createLineBorder(Color.black);
        jPanel1.setBorder(blackline);
        student = stud;
        uni = university;
        setData(student);
    }
    
    public void setData(StudentProfile student) {
        StudentNameTextField.setText(student.getId());
        AgeText.setText(String.valueOf(student.getAge()));
        emailText.setText(student.getEmail());
        phoneText.setText(student.getContact());
        addressText.setText(student.getAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RevenueTitle2 = new javax.swing.JLabel();
        EmployerNameLabel = new javax.swing.JLabel();
        StudentNameTextField = new javax.swing.JTextField();
        ContactLabel = new javax.swing.JLabel();
        AgeText = new javax.swing.JTextField();
        AssociationAgeLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        RevenueTitle2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        RevenueTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RevenueTitle2.setText("View / Update Profile");

        EmployerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EmployerNameLabel.setText("Student Name");

        StudentNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ContactLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ContactLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ContactLabel.setText("Age");

        AgeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        AssociationAgeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AssociationAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AssociationAgeLabel.setText("Email ID");

        emailText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ageLabel.setText("Contact Number");

        phoneText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressLabel.setText("Address");

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateButton.setText("Update Student");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setText("jLabel6");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STUDENT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        addressText.setColumns(20);
        addressText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressText.setRows(5);
        jScrollPane1.setViewportView(addressText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RevenueTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContactLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(AssociationAgeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AgeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StudentNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneText)
                                .addComponent(emailText)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(updateButton)
                        .addGap(84, 84, 84)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(RevenueTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmployerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AssociationAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StudentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(updateButton)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        
        boolean flag = false;
        
        if(StudentNameTextField.getText().isEmpty() || AgeText.getText().isEmpty() || emailText.getText().isEmpty()
                || phoneText.getText().isEmpty() || addressText.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, "Please enter all fields");
        }
        
        String pattern = "^[A-Za-z]+$";
        String number = "^\\d+$";
        String email = "^(.+)@(.+)$";
        String age = "^(\\d*\\.)?\\d+$";
        java.util.regex.Pattern r = java.util.regex.Pattern.compile(pattern);
        java.util.regex.Pattern r1 = java.util.regex.Pattern.compile(number);
        java.util.regex.Pattern r2 = java.util.regex.Pattern.compile(email);
        java.util.regex.Pattern r3 = java.util.regex.Pattern.compile(age);
        Matcher m = r.matcher(StudentNameTextField.getText());
        Matcher m1 = r3.matcher(AgeText.getText());
        Matcher m2 = r2.matcher(emailText.getText());
        Matcher m3 = r1.matcher(phoneText.getText());
        if (((!m.find()) ||  (!m1.find()) ||  (!m2.find()) || (!m3.find()) ) && 
            (!StudentNameTextField.getText().isEmpty() || (!AgeText.getText().isEmpty()) || (!emailText.getText().isEmpty())
                || (!phoneText.getText().isEmpty()) || (!addressText.getText().isEmpty()))) {
            System.out.println("dekh lo>>>");
            flag = true;
            JOptionPane.showMessageDialog(null, "Please enter Valid data");
        }
        
        if(flag == false){
            for(int i = 0; i < uni.getDepartmentList().size(); i ++) {
                System.out.println(student.getId() + "...." + uni.getDepartmentList().get(i).getPersonDirectory().findPerson(student.getId()) + "student ");
                Person p = uni.getDepartmentList().get(i).getPersonDirectory().findPerson(student.getId());
                if (p != null) {
                    p.updatePerson(StudentNameTextField.getText(), Double.parseDouble(AgeText.getText()), emailText.getText(), phoneText.getText(), addressText.getText());
                    StudentProfile st = new StudentProfile(p);
                    System.out.println(p + "p" + st.getAge());
                    JOptionPane.showMessageDialog(this, "Student Details updated successfully");
                    return;
                }
            }
        }
        //        employerDirectory = new EmployerDirectory();
//        student.updateProfile(StudentNameTextField.getText(), Double.parseDouble(AgeText.getText()), emailText.getText(), phoneText.getText(), addressText.getText())
//        Person newPerson = personDirectory.newPerson(StudentNameTextField.getText(), Double.parseDouble(AgeText.getText()), emailText.getText(), phoneText.getText(), addressText.getText(), null, null);
//        studentDirectory.newStudentProfile(newPerson);
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeText;
    private javax.swing.JLabel AssociationAgeLabel;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JLabel EmployerNameLabel;
    private javax.swing.JLabel RevenueTitle2;
    private javax.swing.JTextField StudentNameTextField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextArea addressText;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phoneText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
