/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import static com.db4o.foundation.Iterators.map;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author snehalchavan
 */
public class ManageMenu extends javax.swing.JPanel {

    /**
     * Creates new form ManageMenu
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount user;
    DefaultTableModel model;
    private Restaurant restaurantAssigned;
    
    public ManageMenu(JPanel userProcessContainer,EcoSystem system,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = user;
        showMenu();
        jLabelName.setText("Welcome to "+getRestaurant().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_FoodName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_FoodPrice = new javax.swing.JTextField();
        jButton1AddMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Menu = new javax.swing.JTable();
        jButton_Update = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jButton_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_deleteMenuItem = new javax.swing.JTextField();
        jButtonDeleteItem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Food Name");

        jTextField_FoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FoodNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Price");

        jButton1AddMenu.setText("Add to Menu");
        jButton1AddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AddMenuActionPerformed(evt);
            }
        });

        jTable1Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Menu);

        jButton_Update.setText("Update Menu");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelName.setText("jLabel3");

        jButton_back.setText("Back");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter food item name");

        jButtonDeleteItem.setText("Delete");
        jButtonDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteItemActionPerformed(evt);
            }
        });

        jLabel4.setText("Delete Menu Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_FoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_FoodPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(28, 28, 28)
                                    .addComponent(jTextField_deleteMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(jButtonDeleteItem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1AddMenu))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jButton_back))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_FoodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_FoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Update)
                    .addComponent(jButton1AddMenu))
                .addGap(18, 18, 18)
                .addComponent(jButton_back)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_deleteMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeleteItem))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1AddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AddMenuActionPerformed
        // TODO add your handling code here:
        Restaurant restaurant = getRestaurant();
        
        restaurant.setMenuItem(jTextField_FoodName.getText(), jTextField_FoodPrice.getText());
        jTextField_FoodName.setText("");
        jTextField_FoodPrice.setText("");
        System.out.println("size fter addition"+restaurant.getMenu().size());
        JOptionPane.showMessageDialog(null, "Menu item added");
        showMenu();
                
            
    }//GEN-LAST:event_jButton1AddMenuActionPerformed

    private void jTable1MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MenuMouseClicked
        // TODO add your handling code here:
        Vector elementAt = model.getDataVector().elementAt(jTable1Menu.getSelectedRow());
        jTextField_FoodName.setText((String) elementAt.get(0));
        jTextField_FoodPrice.setText((String) elementAt.get(1));
    }//GEN-LAST:event_jTable1MenuMouseClicked

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        Restaurant restaurant = getRestaurant();
        
        HashMap<String, String> menu = restaurant.getMenu();
        for (Map.Entry<String, String> e : menu.entrySet()){
            if(e.getKey().equals(jTextField_FoodName.getText())){
                menu.remove(e);
                jTextField_FoodName.setText("");
                jTextField_FoodPrice.setText("");
                System.out.println("size fter upadte"+menu.size());
               
                restaurant.setMenuItem(jTextField_FoodName.getText(), jTextField_FoodPrice.getText());
            }
        }
        
        JOptionPane.showMessageDialog(null, "Menu item updated");
        showMenu();

    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jTextField_FoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FoodNameActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdminWorkAreaJPanel adminwjp = (AdminWorkAreaJPanel) component;
//        adminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jButtonDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteItemActionPerformed
        // TODO add your handling code here:
        String menuItem = jTextField_deleteMenuItem.getText();
        Restaurant restaurant = getRestaurant();
        HashMap<String, String> menu = restaurant.getMenu();
        for (Map.Entry<String, String> e : menu.entrySet()){
            if(e.getKey().equals(menuItem)){
                menu.remove(e.getKey());
                System.out.println("size fter deletion"+menu.size());
                jTextField_deleteMenuItem.setText("");
                showMenu();
                JOptionPane.showMessageDialog(null, "Menu Item deleted");
                break;
            }
        }
    }//GEN-LAST:event_jButtonDeleteItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1AddMenu;
    private javax.swing.JButton jButtonDeleteItem;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JButton jButton_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Menu;
    private javax.swing.JTextField jTextField_FoodName;
    private javax.swing.JTextField jTextField_FoodPrice;
    private javax.swing.JTextField jTextField_deleteMenuItem;
    // End of variables declaration//GEN-END:variables

    private void showMenu() {
        Restaurant restaurant = getRestaurant();
        HashMap<String, String> menu = restaurant.getMenu();
        model = new DefaultTableModel();
        jTable1Menu.setModel(model);
        model.addColumn("Food Name");
        model.addColumn("Price");
        for (Map.Entry<String, String> e : menu.entrySet()){
            model.addRow(new Object[]{
                e.getKey(),
                e.getValue()
        });
        }
        
    }

    private Restaurant getRestaurant() {
        ArrayList<Restaurant> restaurantList = system.getRestaurantDirectory().getRestaurantList();
        for(int i=0;i<restaurantList.size();i++){
            if(restaurantList.get(i).getManager().getUsername().equals(user.getUsername())){
                restaurantAssigned = restaurantList.get(i);
            }
        }
        return restaurantAssigned;
    }
}
