/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import static com.db4o.foundation.Iterators.map;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snehalchavan
 */
public class ManageMenu extends javax.swing.JPanel {

    /**
     * Creates new form ManageMenu
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount user;
    DefaultTableModel model;
    private Restaurant restaurantAssigned;
    
    public ManageMenu(JPanel userProcessContainer,EcoSystem system,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = user;
        showMenu();
        jLabelName.setText("Welcome to "+getRestaurant().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_FoodName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_FoodPrice = new javax.swing.JTextField();
        jButton1AddMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Menu = new javax.swing.JTable();
        jButton_Update = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();

        jLabel1.setText("Food Name");

        jTextField_FoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FoodNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Price");

        jButton1AddMenu.setText("Add to Menu");
        jButton1AddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AddMenuActionPerformed(evt);
            }
        });

        jTable1Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Menu);

        jButton_Update.setText("Update Menu");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelName.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1AddMenu))
                            .addComponent(jTextField_FoodPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_FoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabelName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_FoodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_FoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Update)
                    .addComponent(jButton1AddMenu))
                .addGap(139, 139, 139))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1AddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AddMenuActionPerformed
        // TODO add your handling code here:
        Restaurant restaurant = getRestaurant();
        
        restaurant.setMenuItem(jTextField_FoodName.getText(), jTextField_FoodPrice.getText());
        jTextField_FoodName.setText("");
        jTextField_FoodPrice.setText("");
        JOptionPane.showMessageDialog(null, "Menu item added");
        showMenu();
                
            
    }//GEN-LAST:event_jButton1AddMenuActionPerformed

    private void jTable1MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MenuMouseClicked
        // TODO add your handling code here:
        Vector elementAt = model.getDataVector().elementAt(jTable1Menu.getSelectedRow());
        jTextField_FoodName.setText((String) elementAt.get(0));
        jTextField_FoodPrice.setText((String) elementAt.get(1));
    }//GEN-LAST:event_jTable1MenuMouseClicked

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        Restaurant restaurant = getRestaurant();
        
        HashMap<String, String> menu = restaurant.getMenu();
        for (Map.Entry<String, String> e : menu.entrySet()){
            if(e.getKey().equals(jTextField_FoodName.getText())){
                menu.remove(e);
                restaurant.setMenuItem(jTextField_FoodName.getText(), jTextField_FoodPrice.getText());
            }
        }
        
        JOptionPane.showMessageDialog(null, "Menu item updated");
        showMenu();

    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jTextField_FoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FoodNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1AddMenu;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Menu;
    private javax.swing.JTextField jTextField_FoodName;
    private javax.swing.JTextField jTextField_FoodPrice;
    // End of variables declaration//GEN-END:variables

    private void showMenu() {
        Restaurant restaurant = getRestaurant();
        HashMap<String, String> menu = restaurant.getMenu();
        model = new DefaultTableModel();
        jTable1Menu.setModel(model);
        model.addColumn("Food Name");
        model.addColumn("Price");
        for (Map.Entry<String, String> e : menu.entrySet()){
            model.addRow(new Object[]{
                e.getKey(),
                e.getValue()
        });
        }
        
    }

    private Restaurant getRestaurant() {
        ArrayList<Restaurant> restaurantList = system.getRestaurantDirectory().getRestaurantList();
        for(int i=0;i<restaurantList.size();i++){
            if(restaurantList.get(i).getManager().getUsername().equals(user.getUsername())){
                restaurantAssigned = restaurantList.get(i);
            }
        }
        return restaurantAssigned;
    }
}
