/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snehalchavan
 */
public class ManageDeliveryMan extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryMan
     */
    EcoSystem system;
    JPanel userProcessContainer;
    DefaultTableModel model;
    public ManageDeliveryMan(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        DeliverManList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDeliveryManName = new javax.swing.JTextField();
        jButtonCreateDeliverman = new javax.swing.JButton();
        jButton1updateDeliveryman = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDelivermanUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldDeliveryman = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDelDeliveryMan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonDeletedeliverman = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        comboDelivermanList = new javax.swing.JComboBox<>();

        jLabel1.setText("Create DeliveryMan");

        jLabel2.setText("Name");

        jButtonCreateDeliverman.setText("Create");
        jButtonCreateDeliverman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateDelivermanActionPerformed(evt);
            }
        });

        jButton1updateDeliveryman.setText("Update");
        jButton1updateDeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1updateDeliverymanActionPerformed(evt);
            }
        });

        jLabel5.setText("Username");

        jTextFieldDelivermanUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDelivermanUsernameActionPerformed(evt);
            }
        });

        jLabel6.setText("Password");

        jPasswordFieldDeliveryman.setText("jPasswordField1");
        jPasswordFieldDeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldDeliverymanActionPerformed(evt);
            }
        });

        jLabel7.setText("Delivery Man Name");

        jLabel8.setText("Delete DeliveryMan");

        jButtonDeletedeliverman.setText("Delete");
        jButtonDeletedeliverman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletedelivermanActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        comboDelivermanList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboDelivermanListMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboDelivermanListMousePressed(evt);
            }
        });
        comboDelivermanList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDelivermanListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 171, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jButtonDeletedeliverman))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel2)
                                        .addGap(33, 33, 33)
                                        .addComponent(jTextFieldDeliveryManName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton1updateDeliveryman)
                                                    .addComponent(jPasswordFieldDeliveryman)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                                .addComponent(jTextFieldDelivermanUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonCreateDeliverman)))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButtonBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(comboDelivermanList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addGap(86, 86, 86)
                        .addComponent(jTextFieldDelDeliveryMan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDeliveryManName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDelivermanList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDelivermanUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldDeliveryman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateDeliverman)
                    .addComponent(jButton1updateDeliveryman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDelDeliveryMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeletedeliverman)
                    .addComponent(jButtonBack))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateDelivermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateDelivermanActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldDeliveryManName.getText();
        
        Employee deliverman = system.getEmployeeDirectory().createEmployee(name);
        String username = jTextFieldDelivermanUsername.getText();
        String password = String.valueOf(jPasswordFieldDeliveryman.getPassword());
        system.getDeliveryManDirectory().createDeliveryMan(name);
        UserAccount managerAdmin = system.getUserAccountDirectory().createUserAccount(username, password, deliverman, new DeliverManRole());
        jTextFieldDeliveryManName.setText("");
        jTextFieldDelivermanUsername.setText("");
        jPasswordFieldDeliveryman.setText("");
        comboDelivermanList.addItem(system.getDeliveryManDirectory().getDeliverymanList().get(system.getDeliveryManDirectory().getDeliverymanList().size()-1).getName());
        JOptionPane.showMessageDialog(null, "Delivery Man created.");
    }//GEN-LAST:event_jButtonCreateDelivermanActionPerformed

    private void jButton1updateDeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1updateDeliverymanActionPerformed
        // TODO add your handling code here:
        ArrayList<DeliveryMan> deliverymanList = system.getDeliveryManDirectory().getDeliverymanList();
        ArrayList<UserAccount> userAccountList = system.getUserAccountDirectory().getUserAccountList();
        for(int i=0;i<userAccountList.size();i++){
            if(userAccountList.get(i).getEmployee().getName().equals(jTextFieldDeliveryManName.getText())){
                userAccountList.get(i).setPassword(String.valueOf(jPasswordFieldDeliveryman.getPassword()));
                userAccountList.get(i).setUsername(jTextFieldDelivermanUsername.getText());
            }
        }
       
//        DeliverManList();
        jTextFieldDeliveryManName.setText("");
        jTextFieldDelivermanUsername.setText("");
        jPasswordFieldDeliveryman.setText("");
        
        JOptionPane.showMessageDialog(null, "Data updated successfully.");
    }//GEN-LAST:event_jButton1updateDeliverymanActionPerformed

    private void jTextFieldDelivermanUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDelivermanUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDelivermanUsernameActionPerformed

    private void jPasswordFieldDeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldDeliverymanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldDeliverymanActionPerformed

    private void jButtonDeletedelivermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletedelivermanActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldDelDeliveryMan.getText();
        ArrayList<DeliveryMan> deliverymanList = system.getDeliveryManDirectory().getDeliverymanList();
        for(int i=0;i<deliverymanList.size();i++){
            if(deliverymanList.get(i).getName().equals(name)){
                deliverymanList.remove(i);
                System.out.println("deliverman..."+deliverymanList.size());
                comboDelivermanList.removeItem(name);
//                DeliverManList();
                break;
            }

        }
        for(int i=0;i<system.getUserAccountDirectory().getUserAccountList().size();i++){
            if(system.getUserAccountDirectory().getUserAccountList().get(i).getEmployee().getName().equals(name)){
                system.getUserAccountDirectory().getUserAccountList().remove(i);
                System.out.println("user account..."+system.getUserAccountDirectory().getUserAccountList().size());

            }
            if(system.getEmployeeDirectory().getEmployeeList().get(i).getName().equals(name)){
                system.getEmployeeDirectory().getEmployeeList().remove(i);
                System.out.println("employee direc..."+system.getEmployeeDirectory().getEmployeeList().size());
            }
        }
        jTextFieldDelDeliveryMan.setText("");
        JOptionPane.showMessageDialog(null, "Delivery Man Deleted.");
    }//GEN-LAST:event_jButtonDeletedelivermanActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void comboDelivermanListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboDelivermanListMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboDelivermanListMouseClicked

    private void comboDelivermanListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDelivermanListActionPerformed
        // TODO add your handling code here:
        ArrayList<UserAccount> userAccountList = system.getUserAccountDirectory().getUserAccountList();
        String val = comboDelivermanList.getSelectedItem().toString();
        System.out.println("value+++"+val);
        jTextFieldDeliveryManName.setText(val);
        
        for(int i=0;i<userAccountList.size();i++){
            if(userAccountList.get(i).getEmployee().getName().equals(val)){
                jTextFieldDelivermanUsername.setText(userAccountList.get(i).getUsername());
                jPasswordFieldDeliveryman.setText(userAccountList.get(i).getPassword());
                System.out.println("in for loop combo"+userAccountList.get(i).getUsername()+".....");
            }
        }
        
    }//GEN-LAST:event_comboDelivermanListActionPerformed

    private void comboDelivermanListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboDelivermanListMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDelivermanListMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDelivermanList;
    private javax.swing.JButton jButton1updateDeliveryman;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCreateDeliverman;
    private javax.swing.JButton jButtonDeletedeliverman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordFieldDeliveryman;
    private javax.swing.JTextField jTextFieldDelDeliveryMan;
    private javax.swing.JTextField jTextFieldDelivermanUsername;
    private javax.swing.JTextField jTextFieldDeliveryManName;
    // End of variables declaration//GEN-END:variables

    private void DeliverManList() {
        ArrayList<DeliveryMan> deliverymanList = system.getDeliveryManDirectory().getDeliverymanList();
        for(int i=0;i<deliverymanList.size();i++){
            comboDelivermanList.addItem(deliverymanList.get(i).getName());
        }
    }
}
