/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snehalchavan
 */
public class ManageCustomers extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomers
     */
    EcoSystem system;
    JPanel userProcessContainer;
    DefaultTableModel model;
    public ManageCustomers(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        CustomerList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCustomerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCustomerContact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCustomerAddress = new javax.swing.JTextField();
        jButtonCreateCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_customerList = new javax.swing.JTable();
        jButton1upadte = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCustomerusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldCustomer = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDelCust = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonDeleteCustomer = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Create Customer");

        jLabel2.setText("Name");

        jLabel3.setText("Contact number");

        jLabel4.setText("Address");

        jButtonCreateCustomer.setText("Create");
        jButtonCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateCustomerActionPerformed(evt);
            }
        });

        jTable_customerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_customerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_customerListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_customerList);

        jButton1upadte.setText("Update");
        jButton1upadte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1upadteActionPerformed(evt);
            }
        });

        jLabel5.setText("Username");

        jTextFieldCustomerusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerusernameActionPerformed(evt);
            }
        });

        jLabel6.setText("Password");

        jPasswordFieldCustomer.setText("jPasswordField1");
        jPasswordFieldCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldCustomerActionPerformed(evt);
            }
        });

        jLabel7.setText("Cutomer Name");

        jLabel8.setText("Delete Customer");

        jButtonDeleteCustomer.setText("Delete");
        jButtonDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCustomerActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonCreateCustomer)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDeleteCustomer)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1upadte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCustomerusername)
                                    .addComponent(jPasswordFieldCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCustomerAddress)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCustomerContact, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButtonBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addGap(86, 86, 86)
                        .addComponent(jTextFieldDelCust, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldCustomerContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldCustomerusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordFieldCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateCustomer)
                    .addComponent(jButton1upadte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDelCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteCustomer)
                    .addComponent(jButtonBack))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateCustomerActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldCustomerName.getText();
        String contact = jTextFieldCustomerContact.getText();
        String address = jTextFieldCustomerAddress.getText();
        Employee customer = system.getEmployeeDirectory().createEmployee(name);
        String username = jTextFieldCustomerusername.getText();
        String password = String.valueOf(jPasswordFieldCustomer.getPassword());
        system.getCustomerDirectory().newCustomer(name, contact, address);
        UserAccount managerAdmin = system.getUserAccountDirectory().createUserAccount(username, password, customer, new CustomerRole());
        jTextFieldCustomerName.setText("");
        jTextFieldCustomerusername.setText("");
        jPasswordFieldCustomer.setText("");
        jTextFieldCustomerContact.setText("");
        jTextFieldCustomerAddress.setText("");
        CustomerList();
        JOptionPane.showMessageDialog(null, "Customer created.");
    }//GEN-LAST:event_jButtonCreateCustomerActionPerformed

    private void jButton1upadteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1upadteActionPerformed
        // TODO add your handling code here:
        ArrayList<Customer> customerList = system.getCustomerDirectory().getCustomerList();
        ArrayList<UserAccount> userAccountList = system.getUserAccountDirectory().getUserAccountList();
        for(int i=0;i<userAccountList.size();i++){
            if(userAccountList.get(i).getEmployee().getName().equals(jTextFieldCustomerName.getText())){
                userAccountList.get(i).setPassword(String.valueOf(jPasswordFieldCustomer.getPassword()));
                userAccountList.get(i).setUsername(jTextFieldCustomerusername.getText());
            }
        }
        for(int i=0;i<customerList.size();i++){
            if(customerList.get(i).getCustomerName().equals(jTextFieldCustomerName.getText())){
                customerList.get(i).setContactNumber(jTextFieldCustomerContact.getText());
                customerList.get(i).setAddress(jTextFieldCustomerAddress.getText());
            }
        }
        CustomerList();
        jTextFieldCustomerName.setText("");
        jTextFieldCustomerusername.setText("");
        jPasswordFieldCustomer.setText("");
        jTextFieldCustomerContact.setText("");
        jTextFieldCustomerAddress.setText("");
        JOptionPane.showMessageDialog(null, "Data updated successfully.");
    }//GEN-LAST:event_jButton1upadteActionPerformed

    private void jTextFieldCustomerusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerusernameActionPerformed

    private void jPasswordFieldCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldCustomerActionPerformed

    private void jTable_customerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_customerListMouseClicked
        // TODO add your handling code here:
        Vector elementAt = model.getDataVector().elementAt(jTable_customerList.getSelectedRow());
        jTextFieldCustomerName.setText((String) elementAt.get(0));
        jTextFieldCustomerContact.setText((String) elementAt.get(1));
        jTextFieldCustomerAddress.setText((String) elementAt.get(2));
        ArrayList<UserAccount> userAccountList = system.getUserAccountDirectory().getUserAccountList();
        for(int i=0;i<userAccountList.size();i++){
            if(userAccountList.get(i).getEmployee().getName().equals(jTextFieldCustomerName.getText())){
                jTextFieldCustomerusername.setText(userAccountList.get(i).getUsername());
                jPasswordFieldCustomer.setText(userAccountList.get(i).getPassword());
            }
        }
    }//GEN-LAST:event_jTable_customerListMouseClicked

    private void jButtonDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCustomerActionPerformed
        // TODO add your handling code here:
        String custName = jTextFieldDelCust.getText();
        ArrayList<Customer> customerList = system.getCustomerDirectory().getCustomerList();
        for(int i=0;i<customerList.size();i++){
            if(customerList.get(i).getCustomerName().equals(custName)){
                customerList.remove(i);
                CustomerList();
                break;
            }
            
        }
        for(int i=0;i<system.getUserAccountDirectory().getUserAccountList().size();i++){
            if(system.getUserAccountDirectory().getUserAccountList().get(i).getEmployee().getName().equals(custName)){
                system.getUserAccountDirectory().getUserAccountList().remove(i);
                
            }
            if(system.getEmployeeDirectory().getEmployeeList().get(i).getName().equals(custName)){
                    system.getEmployeeDirectory().getEmployeeList().remove(i);
            }
        }
        jTextFieldDelCust.setText("");
        JOptionPane.showMessageDialog(null, "Customer Deleted.");
    }//GEN-LAST:event_jButtonDeleteCustomerActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1upadte;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCreateCustomer;
    private javax.swing.JButton jButtonDeleteCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordFieldCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_customerList;
    private javax.swing.JTextField jTextFieldCustomerAddress;
    private javax.swing.JTextField jTextFieldCustomerContact;
    private javax.swing.JTextField jTextFieldCustomerName;
    private javax.swing.JTextField jTextFieldCustomerusername;
    private javax.swing.JTextField jTextFieldDelCust;
    // End of variables declaration//GEN-END:variables

    private void CustomerList() {
        ArrayList<UserAccount> userAccountList = system.getUserAccountDirectory().getUserAccountList();
        ArrayList<Customer> customerList = system.getCustomerDirectory().getCustomerList();
         model = new DefaultTableModel();
        jTable_customerList.setModel(model);
        model.addColumn("Name");
        model.addColumn("Contact Number");
        model.addColumn("Address");
        for(int i=0;i<customerList.size();i++){
                model.addRow(new Object[]{
                    customerList.get(i).getCustomerName(),
                    customerList.get(i).getContactNumber(),
                    customerList.get(i).getAddress()
                });
        }
    }
}
