/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author snehalchavan
 */
public class addressJpanel extends javax.swing.JPanel {

    /**
     * Creates new form addressJpanel
     */
    Person person;
    
    public addressJpanel(Person person) {
        initComponents();
        
        this.person = person;
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_address = new javax.swing.JPanel();
        lbl_street = new javax.swing.JLabel();
        lbl_city = new javax.swing.JLabel();
        lbl_state = new javax.swing.JLabel();
        lbl_zipcode = new javax.swing.JLabel();
        txt_street = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        txt_state = new javax.swing.JTextField();
        txt_zipcode = new javax.swing.JTextField();
        lbl_address = new javax.swing.JLabel();
        btnSaveaddress = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 219, 219));

        jpanel_address.setBackground(new java.awt.Color(243, 219, 219));

        lbl_street.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_street.setText("Street");

        lbl_city.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_city.setText("City");

        lbl_state.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_state.setText("State");

        lbl_zipcode.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_zipcode.setText("Zip Code");

        txt_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stateActionPerformed(evt);
            }
        });

        lbl_address.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbl_address.setText("Address");

        btnSaveaddress.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnSaveaddress.setText("Save");
        btnSaveaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveaddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_addressLayout = new javax.swing.GroupLayout(jpanel_address);
        jpanel_address.setLayout(jpanel_addressLayout);
        jpanel_addressLayout.setHorizontalGroup(
            jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_addressLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_addressLayout.createSequentialGroup()
                        .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_city)
                            .addComponent(lbl_street)
                            .addComponent(lbl_state)
                            .addComponent(lbl_zipcode))
                        .addGap(52, 52, 52)
                        .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_zipcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_street, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_state, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_city, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_addressLayout.createSequentialGroup()
                        .addComponent(lbl_address)
                        .addGap(113, 113, 113))))
            .addGroup(jpanel_addressLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnSaveaddress)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpanel_addressLayout.setVerticalGroup(
            jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_addressLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_address)
                .addGap(18, 18, 18)
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_street))
                .addGap(18, 18, 18)
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_city, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_state))
                .addGap(18, 18, 18)
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_zipcode)
                    .addComponent(txt_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveaddress)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_address, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jpanel_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stateActionPerformed

    private void btnSaveaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveaddressActionPerformed
        // TODO add your handling code here:
        person.setStreet(txt_street.getText());
        person.setCity(txt_city.getText());
        person.setState(txt_state.getText());
        person.setZipcode(txt_zipcode.getText());
        JOptionPane.showMessageDialog(this, "Address saved.");
        Clearselection();
    }//GEN-LAST:event_btnSaveaddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveaddress;
    private javax.swing.JPanel jpanel_address;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_street;
    private javax.swing.JLabel lbl_zipcode;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_state;
    private javax.swing.JTextField txt_street;
    private javax.swing.JTextField txt_zipcode;
    // End of variables declaration//GEN-END:variables

    private void Clearselection() {
        txt_city.setText("");
        txt_state.setText("");
        txt_street.setText("");
        txt_zipcode.setText("");
    }
}
