/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Bank;
import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author snehalchavan
 */
public class BankJpanel extends javax.swing.JPanel {

    /**
     * Creates new form BankJpanel
     */
    Person person;
    Bank bank;
    
    public BankJpanel(Person person,Bank bank) {
        initComponents();
        this.person = person;
        this.bank = bank;
//        this.bank = person.getSavingaccount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_bank = new javax.swing.JPanel();
        lbl_bankname = new javax.swing.JLabel();
        lbl_routing = new javax.swing.JLabel();
        lbl_accno = new javax.swing.JLabel();
        lbl_balance = new javax.swing.JLabel();
        lbl_acctype = new javax.swing.JLabel();
        txt_routing = new javax.swing.JTextField();
        txt_bankname = new javax.swing.JTextField();
        txt_balance = new javax.swing.JTextField();
        txt_accno = new javax.swing.JTextField();
        lbl_bankdetails = new javax.swing.JLabel();
        combo_acctype = new javax.swing.JComboBox<>();
        btnbanksave = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 219, 219));

        jpanel_bank.setBackground(new java.awt.Color(243, 219, 219));

        lbl_bankname.setText("Bank Name");

        lbl_routing.setText("Routing Number");

        lbl_accno.setText("Account Number");

        lbl_balance.setText("Balance");

        lbl_acctype.setText("Account Type");

        txt_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_balanceActionPerformed(evt);
            }
        });

        lbl_bankdetails.setText("Bank Details");

        combo_acctype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Checkin", " " }));
        combo_acctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_acctypeActionPerformed(evt);
            }
        });

        btnbanksave.setText("Save");
        btnbanksave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbanksaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_bankLayout = new javax.swing.GroupLayout(jpanel_bank);
        jpanel_bank.setLayout(jpanel_bankLayout);
        jpanel_bankLayout.setHorizontalGroup(
            jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_bankLayout.createSequentialGroup()
                .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_bankLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_acctype)
                            .addComponent(lbl_balance))
                        .addGap(40, 40, 40)
                        .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_acctype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbanksave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_bankLayout.createSequentialGroup()
                        .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_bankLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lbl_bankname))
                            .addGroup(jpanel_bankLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lbl_routing))
                            .addGroup(jpanel_bankLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lbl_accno)))
                        .addGap(37, 37, 37)
                        .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_accno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_routing, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bankname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_bankLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lbl_bankdetails)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_bankLayout.setVerticalGroup(
            jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_bankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_bankdetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bankname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_routing)
                    .addComponent(txt_routing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_accno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_balance))
                .addGap(18, 18, 18)
                .addGroup(jpanel_bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_acctype)
                    .addComponent(combo_acctype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbanksave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel_bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel_bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_acctypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_acctypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_acctypeActionPerformed

    private void txt_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_balanceActionPerformed

    private void btnbanksaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbanksaveActionPerformed
        // TODO add your handling code here:
//        bank.setBname(txt_bankname.getText());
//        bank.setRoutingno(txt_routing.getText());
//        bank.setAccountno(txt_accno.getText());
//        bank.setBalance(txt_balance.getText());
//        bank.setAcctype(radiobtnSaving.getText());
        
        if("Savings".equals((String) combo_acctype.getSelectedItem())){
            bank.setAcctypesave((String) combo_acctype.getSelectedItem());
            bank.setAccountnosave(txt_accno.getText());
            bank.setBnamesave(txt_bankname.getText());
            bank.setBalancesave(txt_balance.getText());
            bank.setRoutingnosave(txt_routing.getText());
            person.setSavingaccount(bank);
            System.out.println("in saving");
        }else{
            
            bank.setAcctypecheck((String) combo_acctype.getSelectedItem());
            bank.setAccountnocheck(txt_accno.getText());
            bank.setBnamecheck(txt_bankname.getText());
            bank.setBalancecheck(txt_balance.getText());
            bank.setRoutingnocheck(txt_routing.getText());
            person.setCheckinaccount(bank);
            System.out.println("in checkin");
        }
        
        JOptionPane.showMessageDialog(this, "Bank details saved.");
        Clearselection();
    }//GEN-LAST:event_btnbanksaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbanksave;
    private javax.swing.JComboBox<String> combo_acctype;
    private javax.swing.JPanel jpanel_bank;
    private javax.swing.JLabel lbl_accno;
    private javax.swing.JLabel lbl_acctype;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JLabel lbl_bankdetails;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_routing;
    private javax.swing.JTextField txt_accno;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_bankname;
    private javax.swing.JTextField txt_routing;
    // End of variables declaration//GEN-END:variables

    private void Clearselection() {
        txt_accno.setText("");
        txt_balance.setText("");
        txt_bankname.setText("");
        txt_routing.setText("");
    }
}
