/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Person;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author snehalchavan
 */
public class driverLicenceJpanel extends javax.swing.JPanel {

    /**
     * Creates new form driverLicenceJpanel
     */
    Person person;
    public driverLicenceJpanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_licence = new javax.swing.JPanel();
        lbl_licencenum = new javax.swing.JLabel();
        lbl_dtissue = new javax.swing.JLabel();
        lbl_dtexpire = new javax.swing.JLabel();
        lbl_bloodtype = new javax.swing.JLabel();
        txt_dtissue = new javax.swing.JTextField();
        txt_dtexpire = new javax.swing.JTextField();
        txt_licencenum = new javax.swing.JTextField();
        txt_bloodtype = new javax.swing.JTextField();
        lblLicence = new javax.swing.JLabel();
        btnDriverLicencesave = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 219, 219));

        jpanel_licence.setBackground(new java.awt.Color(243, 219, 219));

        lbl_licencenum.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_licencenum.setText("Licence Number");

        lbl_dtissue.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_dtissue.setText("Date of Issue");

        lbl_dtexpire.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_dtexpire.setText("Date of Expiration");

        lbl_bloodtype.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_bloodtype.setText("Blood Type");

        txt_licencenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_licencenumActionPerformed(evt);
            }
        });

        lblLicence.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lblLicence.setText("Driver's Licence");

        btnDriverLicencesave.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnDriverLicencesave.setText("Save");
        btnDriverLicencesave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverLicencesaveActionPerformed(evt);
            }
        });

        lblImage.setBackground(new java.awt.Color(243, 219, 219));
        lblImage.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N

        btnUpload.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_licenceLayout = new javax.swing.GroupLayout(jpanel_licence);
        jpanel_licence.setLayout(jpanel_licenceLayout);
        jpanel_licenceLayout.setHorizontalGroup(
            jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_licenceLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_licenceLayout.createSequentialGroup()
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_licencenum)
                            .addComponent(lbl_dtissue))
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_licenceLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblLicence))
                            .addGroup(jpanel_licenceLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(txt_dtissue, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpanel_licenceLayout.createSequentialGroup()
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_dtexpire)
                            .addComponent(lbl_bloodtype))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDriverLicencesave)
                            .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_licencenum, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_dtexpire, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(txt_bloodtype))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpload)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpanel_licenceLayout.setVerticalGroup(
            jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_licenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLicence)
                .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_licenceLayout.createSequentialGroup()
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_licencenum)
                            .addComponent(txt_licencenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dtissue)
                            .addComponent(txt_dtissue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dtexpire)
                            .addComponent(txt_dtexpire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_licenceLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_bloodtype))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_licenceLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txt_bloodtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDriverLicencesave)
                    .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel_licence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel_licence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_licencenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_licencenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_licencenumActionPerformed

    private void btnDriverLicencesaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverLicencesaveActionPerformed
        // TODO add your handling code here:
        person.setLicenseno(txt_licencenum.getText());
        person.setDtofissue(txt_dtissue.getText());
        person.setDtofexpire(txt_dtexpire.getText());
        person.setBloodtype(txt_bloodtype.getText());
        JOptionPane.showMessageDialog(this, "Driving Licence details saved successfully");
        clearSelection();
        
    }//GEN-LAST:event_btnDriverLicencesaveActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        String folder = System.getProperty("user.dir");
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(choose);
        File f = choose.getSelectedFile();
        String filename = f.getAbsolutePath();
        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(lblImage.getWidth(),lblImage.getHeight(),Image.SCALE_SMOOTH);
        lblImage.setIcon(icon);

         
    }//GEN-LAST:event_btnUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDriverLicencesave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JPanel jpanel_licence;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLicence;
    private javax.swing.JLabel lbl_bloodtype;
    private javax.swing.JLabel lbl_dtexpire;
    private javax.swing.JLabel lbl_dtissue;
    private javax.swing.JLabel lbl_licencenum;
    private javax.swing.JTextField txt_bloodtype;
    private javax.swing.JTextField txt_dtexpire;
    private javax.swing.JTextField txt_dtissue;
    private javax.swing.JTextField txt_licencenum;
    // End of variables declaration//GEN-END:variables

    private void clearSelection() {
        txt_licencenum.setText("");
        txt_bloodtype.setText("");
        txt_dtissue.setText("");
        txt_dtexpire.setText("");
    }
}
