/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Bank;
import Model.Person;

/**
 *
 * @author snehalchavan
 */
public class ViewJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJpanel
     */
    Person person;
    Bank savebank,checkinbank;
    
    public ViewJpanel(Person person) {
        initComponents();
        this.person = person; 
//        this.savebank = person.getSavingaccount();
//        this.checkinbank = person.getCheckinaccount();
//        savebank = person.getSavingaccount();
//        checkinbank = person.getSavingaccount();
//        address = person.getAddress();
        displayAddressDetails();
        displayDemographicDetails();
        displayLicenseDetails();
        displayMedicalRecord();
        if(person.getSavingaccount() != null){
            displaySavingBankDetails();        
        }
        
        if(person.getCheckinaccount() != null){
            displayCheckinBankDetails();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpanel_demographics = new javax.swing.JPanel();
        lbl_firstname = new javax.swing.JLabel();
        lbl_dob = new javax.swing.JLabel();
        lbl_last = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        lbl_height = new javax.swing.JLabel();
        lbl_weight = new javax.swing.JLabel();
        lbl_ssn = new javax.swing.JLabel();
        txt_first = new javax.swing.JTextField();
        txt_last = new javax.swing.JTextField();
        lbl_phone = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_weight = new javax.swing.JTextField();
        txt_height = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_ssn = new javax.swing.JTextField();
        lbldemographics = new javax.swing.JLabel();
        jpanel_medical = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_allergy1 = new javax.swing.JLabel();
        lbl_recordno = new javax.swing.JLabel();
        lbl_allergy2 = new javax.swing.JLabel();
        lbl_allergy3 = new javax.swing.JLabel();
        txt_recordno = new javax.swing.JTextField();
        txt_allergy3 = new javax.swing.JTextField();
        txt_allergy1 = new javax.swing.JTextField();
        txt_allergy2 = new javax.swing.JTextField();
        jpanel_savingbank = new javax.swing.JPanel();
        lbl_banknamesav = new javax.swing.JLabel();
        lbl_routingsav = new javax.swing.JLabel();
        lbl_accnosav = new javax.swing.JLabel();
        lbl_balancesav = new javax.swing.JLabel();
        lbl_acctypesav = new javax.swing.JLabel();
        txt_routingsav = new javax.swing.JTextField();
        txt_banknamesav = new javax.swing.JTextField();
        txt_balancesav = new javax.swing.JTextField();
        txt_accnosav = new javax.swing.JTextField();
        lbl_bank = new javax.swing.JLabel();
        txt_savingtype = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        jpanel_checkinbank = new javax.swing.JPanel();
        lbl_banknamecheckin = new javax.swing.JLabel();
        lbl_routingcheckin = new javax.swing.JLabel();
        lbl_accnocheckin = new javax.swing.JLabel();
        lbl_balancecheckin = new javax.swing.JLabel();
        lbl_acctypecheckin = new javax.swing.JLabel();
        txt_routingcheckin = new javax.swing.JTextField();
        txt_banknamecheckin = new javax.swing.JTextField();
        txt_balancecheckin = new javax.swing.JTextField();
        txt_accnocheckin = new javax.swing.JTextField();
        lbl_bank1 = new javax.swing.JLabel();
        txt_checkintype = new javax.swing.JTextField();
        jpanel_address = new javax.swing.JPanel();
        lbl_street = new javax.swing.JLabel();
        lbl_city = new javax.swing.JLabel();
        lbl_state = new javax.swing.JLabel();
        lbl_zipcode = new javax.swing.JLabel();
        txt_street = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        txt_state = new javax.swing.JTextField();
        txt_zipcode = new javax.swing.JTextField();
        lbl_address = new javax.swing.JLabel();
        jpanel_licence = new javax.swing.JPanel();
        lbl_dtexpire = new javax.swing.JLabel();
        lbl_bloodtype = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_licencenum = new javax.swing.JTextField();
        txt_dtissue = new javax.swing.JTextField();
        lbl_licencenum = new javax.swing.JLabel();
        lbl_dtissue = new javax.swing.JLabel();
        txt_dtexpire = new javax.swing.JTextField();
        txt_bloodtype = new javax.swing.JTextField();

        jLabel5.setText("Blood Type");

        jLabel6.setText("Blood Type");

        setBackground(new java.awt.Color(217, 243, 243));

        jpanel_demographics.setBackground(new java.awt.Color(217, 243, 243));
        jpanel_demographics.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N

        lbl_firstname.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_firstname.setText("First Name");

        lbl_dob.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_dob.setText("DOB");

        lbl_last.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_last.setText("Last Name");

        lbl_age.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_age.setText("Age");

        lbl_height.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_height.setText("Height");

        lbl_weight.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_weight.setText("Weight");

        lbl_ssn.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_ssn.setText("SSN");

        txt_last.setEditable(false);
        txt_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastActionPerformed(evt);
            }
        });

        lbl_phone.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_phone.setText("Phone Number");

        txt_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dobActionPerformed(evt);
            }
        });

        txt_age.setEditable(false);

        txt_weight.setEditable(false);
        txt_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_weightActionPerformed(evt);
            }
        });

        txt_height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_heightActionPerformed(evt);
            }
        });

        txt_ssn.setEditable(false);
        txt_ssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ssnActionPerformed(evt);
            }
        });

        lbldemographics.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbldemographics.setText("Demographics");

        javax.swing.GroupLayout jpanel_demographicsLayout = new javax.swing.GroupLayout(jpanel_demographics);
        jpanel_demographics.setLayout(jpanel_demographicsLayout);
        jpanel_demographicsLayout.setHorizontalGroup(
            jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_demographicsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_phone)
                    .addComponent(lbl_height)
                    .addComponent(lbl_dob)
                    .addComponent(lbl_firstname))
                .addGap(18, 18, 18)
                .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txt_height)
                    .addComponent(txt_dob)
                    .addComponent(txt_first))
                .addGap(147, 147, 147)
                .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel_demographicsLayout.createSequentialGroup()
                        .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_weight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_age, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_last, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_last, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_weight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_demographicsLayout.createSequentialGroup()
                        .addComponent(lbl_ssn)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_demographicsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldemographics)
                .addGap(290, 290, 290))
        );
        jpanel_demographicsLayout.setVerticalGroup(
            jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_demographicsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbldemographics)
                .addGap(18, 18, 18)
                .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_firstname)
                    .addComponent(txt_last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_last, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_age, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dob))
                .addGap(9, 9, 9)
                .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_weight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_weight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_height, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_demographicsLayout.createSequentialGroup()
                        .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_demographicsLayout.createSequentialGroup()
                        .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_demographicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_ssn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );

        jpanel_medical.setBackground(new java.awt.Color(217, 243, 243));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel7.setText("Medical Record");

        lbl_allergy1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_allergy1.setText("Allergy 1");

        lbl_recordno.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_recordno.setText("Record Number");

        lbl_allergy2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_allergy2.setText("Allergy 2");

        lbl_allergy3.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_allergy3.setText("Allergy 3");

        txt_recordno.setEditable(false);

        txt_allergy3.setEditable(false);

        txt_allergy1.setEditable(false);

        txt_allergy2.setEditable(false);

        javax.swing.GroupLayout jpanel_medicalLayout = new javax.swing.GroupLayout(jpanel_medical);
        jpanel_medical.setLayout(jpanel_medicalLayout);
        jpanel_medicalLayout.setHorizontalGroup(
            jpanel_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_medicalLayout.createSequentialGroup()
                .addGroup(jpanel_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_medicalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanel_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_recordno)
                            .addComponent(lbl_allergy1)
                            .addComponent(lbl_allergy2)
                            .addComponent(lbl_allergy3))
                        .addGap(36, 36, 36)
                        .addGroup(jpanel_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_recordno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_allergy1)
                            .addComponent(txt_allergy2)
                            .addComponent(txt_allergy3)))
                    .addGroup(jpanel_medicalLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jpanel_medicalLayout.setVerticalGroup(
            jpanel_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_medicalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addGroup(jpanel_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_recordno)
                    .addComponent(txt_recordno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_allergy1)
                    .addComponent(txt_allergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_allergy2)
                    .addComponent(txt_allergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_allergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_allergy3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanel_savingbank.setBackground(new java.awt.Color(217, 243, 243));

        lbl_banknamesav.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_banknamesav.setText("Bank Name");

        lbl_routingsav.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_routingsav.setText("Routing Number");

        lbl_accnosav.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_accnosav.setText("Account Number");

        lbl_balancesav.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_balancesav.setText("Balance");

        lbl_acctypesav.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_acctypesav.setText("Account Type");

        txt_routingsav.setEditable(false);

        txt_banknamesav.setEditable(false);

        txt_balancesav.setEditable(false);

        txt_accnosav.setEditable(false);

        lbl_bank.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbl_bank.setText("Saving Account");

        txt_savingtype.setEditable(false);

        javax.swing.GroupLayout jpanel_savingbankLayout = new javax.swing.GroupLayout(jpanel_savingbank);
        jpanel_savingbank.setLayout(jpanel_savingbankLayout);
        jpanel_savingbankLayout.setHorizontalGroup(
            jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_savingbankLayout.createSequentialGroup()
                .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel_savingbankLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_savingbankLayout.createSequentialGroup()
                                .addComponent(lbl_accnosav, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_savingbankLayout.createSequentialGroup()
                                .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_acctypesav)
                                    .addComponent(lbl_balancesav, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))
                        .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_accnosav, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txt_balancesav)
                            .addComponent(txt_savingtype)))
                    .addGroup(jpanel_savingbankLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_banknamesav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_routingsav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_banknamesav, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txt_routingsav))))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_savingbankLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_bank)
                .addGap(87, 87, 87))
        );
        jpanel_savingbankLayout.setVerticalGroup(
            jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_savingbankLayout.createSequentialGroup()
                .addComponent(lbl_bank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_banknamesav)
                    .addComponent(txt_banknamesav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_routingsav)
                    .addComponent(txt_routingsav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_accnosav)
                    .addComponent(txt_accnosav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_balancesav)
                    .addComponent(txt_balancesav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_savingbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_acctypesav)
                    .addComponent(txt_savingtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        title.setText("Personal Information");

        jpanel_checkinbank.setBackground(new java.awt.Color(217, 243, 243));

        lbl_banknamecheckin.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_banknamecheckin.setText("Bank Name");

        lbl_routingcheckin.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_routingcheckin.setText("Routing Number");

        lbl_accnocheckin.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_accnocheckin.setText("Account Number");

        lbl_balancecheckin.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_balancecheckin.setText("Balance");

        lbl_acctypecheckin.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_acctypecheckin.setText("Account Type");

        txt_routingcheckin.setEditable(false);

        txt_banknamecheckin.setEditable(false);

        txt_balancecheckin.setEditable(false);

        txt_accnocheckin.setEditable(false);

        lbl_bank1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbl_bank1.setText("Checkin Account");

        txt_checkintype.setEditable(false);

        javax.swing.GroupLayout jpanel_checkinbankLayout = new javax.swing.GroupLayout(jpanel_checkinbank);
        jpanel_checkinbank.setLayout(jpanel_checkinbankLayout);
        jpanel_checkinbankLayout.setHorizontalGroup(
            jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_checkinbankLayout.createSequentialGroup()
                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_checkinbankLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lbl_bank1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_checkinbankLayout.createSequentialGroup()
                        .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel_checkinbankLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_balancecheckin)
                                    .addComponent(lbl_acctypecheckin))
                                .addGap(29, 29, 29)
                                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_checkintype)
                                    .addComponent(txt_balancecheckin)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel_checkinbankLayout.createSequentialGroup()
                                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_banknamecheckin)
                                    .addComponent(lbl_routingcheckin)
                                    .addComponent(lbl_accnocheckin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_routingcheckin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                        .addComponent(txt_banknamecheckin, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txt_accnocheckin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(75, 75, 75)))
                .addContainerGap())
        );
        jpanel_checkinbankLayout.setVerticalGroup(
            jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_checkinbankLayout.createSequentialGroup()
                .addComponent(lbl_bank1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_banknamecheckin)
                    .addComponent(txt_banknamecheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_routingcheckin)
                    .addComponent(txt_routingcheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_accnocheckin)
                    .addComponent(txt_accnocheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_balancecheckin)
                    .addComponent(txt_balancecheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_checkinbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_acctypecheckin)
                    .addComponent(txt_checkintype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanel_address.setBackground(new java.awt.Color(217, 243, 243));

        lbl_street.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_street.setText("Street");

        lbl_city.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_city.setText("City");

        lbl_state.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_state.setText("State");

        lbl_zipcode.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_zipcode.setText("Zip Code");

        txt_street.setEditable(false);

        txt_city.setEditable(false);

        txt_state.setEditable(false);
        txt_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stateActionPerformed(evt);
            }
        });

        txt_zipcode.setEditable(false);

        lbl_address.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbl_address.setText("Address");

        javax.swing.GroupLayout jpanel_addressLayout = new javax.swing.GroupLayout(jpanel_address);
        jpanel_address.setLayout(jpanel_addressLayout);
        jpanel_addressLayout.setHorizontalGroup(
            jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_addressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_addressLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_state, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_city, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_street, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(lbl_zipcode))
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_addressLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_street, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_addressLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_state, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txt_zipcode))))
                .addGap(54, 54, 54))
            .addGroup(jpanel_addressLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lbl_address)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_addressLayout.setVerticalGroup(
            jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_addressLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lbl_address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_street))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_city, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_state))
                .addGap(18, 18, 18)
                .addGroup(jpanel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_zipcode)
                    .addComponent(txt_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jpanel_licence.setBackground(new java.awt.Color(217, 243, 243));

        lbl_dtexpire.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_dtexpire.setText("Date of Expiration");

        lbl_bloodtype.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lbl_bloodtype.setText("Blood Type");
        lbl_bloodtype.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel1.setText("Driver's Licence");

        txt_licencenum.setEditable(false);
        txt_licencenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_licencenumActionPerformed(evt);
            }
        });

        txt_dtissue.setEditable(false);

        lbl_licencenum.setText("Licence Number");

        lbl_dtissue.setText("Date of Issue");

        txt_dtexpire.setEditable(false);

        txt_bloodtype.setEditable(false);
        txt_bloodtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bloodtypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_licenceLayout = new javax.swing.GroupLayout(jpanel_licence);
        jpanel_licence.setLayout(jpanel_licenceLayout);
        jpanel_licenceLayout.setHorizontalGroup(
            jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_licenceLayout.createSequentialGroup()
                .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_licenceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_licenceLayout.createSequentialGroup()
                                .addComponent(lbl_licencenum)
                                .addGap(18, 18, 18))
                            .addGroup(jpanel_licenceLayout.createSequentialGroup()
                                .addComponent(lbl_dtissue, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_dtissue, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(txt_licencenum))
                        .addGap(81, 81, 81)
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_dtexpire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_bloodtype, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(33, 33, 33)
                        .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_dtexpire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bloodtype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_licenceLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jpanel_licenceLayout.setVerticalGroup(
            jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_licenceLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_licencenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_licencenum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dtexpire)
                    .addComponent(txt_dtexpire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel_licenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dtissue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dtissue)
                    .addComponent(lbl_bloodtype)
                    .addComponent(txt_bloodtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jpanel_savingbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpanel_medical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jpanel_address, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jpanel_demographics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jpanel_licence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpanel_checkinbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpanel_demographics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel_medical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel_checkinbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel_savingbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanel_licence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_heightActionPerformed

    private void txt_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_weightActionPerformed

    private void txt_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastActionPerformed

    private void txt_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stateActionPerformed

    private void txt_licencenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_licencenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_licencenumActionPerformed

    private void txt_bloodtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bloodtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bloodtypeActionPerformed

    private void txt_ssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ssnActionPerformed

    private void txt_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dobActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jpanel_address;
    private javax.swing.JPanel jpanel_checkinbank;
    private javax.swing.JPanel jpanel_demographics;
    private javax.swing.JPanel jpanel_licence;
    private javax.swing.JPanel jpanel_medical;
    private javax.swing.JPanel jpanel_savingbank;
    private javax.swing.JLabel lbl_accnocheckin;
    private javax.swing.JLabel lbl_accnosav;
    private javax.swing.JLabel lbl_acctypecheckin;
    private javax.swing.JLabel lbl_acctypesav;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_allergy1;
    private javax.swing.JLabel lbl_allergy2;
    private javax.swing.JLabel lbl_allergy3;
    private javax.swing.JLabel lbl_balancecheckin;
    private javax.swing.JLabel lbl_balancesav;
    private javax.swing.JLabel lbl_bank;
    private javax.swing.JLabel lbl_bank1;
    private javax.swing.JLabel lbl_banknamecheckin;
    private javax.swing.JLabel lbl_banknamesav;
    private javax.swing.JLabel lbl_bloodtype;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_dtexpire;
    private javax.swing.JLabel lbl_dtissue;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_height;
    private javax.swing.JLabel lbl_last;
    private javax.swing.JLabel lbl_licencenum;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_recordno;
    private javax.swing.JLabel lbl_routingcheckin;
    private javax.swing.JLabel lbl_routingsav;
    private javax.swing.JLabel lbl_ssn;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_street;
    private javax.swing.JLabel lbl_weight;
    private javax.swing.JLabel lbl_zipcode;
    private javax.swing.JLabel lbldemographics;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txt_accnocheckin;
    private javax.swing.JTextField txt_accnosav;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_allergy1;
    private javax.swing.JTextField txt_allergy2;
    private javax.swing.JTextField txt_allergy3;
    private javax.swing.JTextField txt_balancecheckin;
    private javax.swing.JTextField txt_balancesav;
    private javax.swing.JTextField txt_banknamecheckin;
    private javax.swing.JTextField txt_banknamesav;
    private javax.swing.JTextField txt_bloodtype;
    private javax.swing.JTextField txt_checkintype;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_dtexpire;
    private javax.swing.JTextField txt_dtissue;
    private javax.swing.JTextField txt_first;
    private javax.swing.JTextField txt_height;
    private javax.swing.JTextField txt_last;
    private javax.swing.JTextField txt_licencenum;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_recordno;
    private javax.swing.JTextField txt_routingcheckin;
    private javax.swing.JTextField txt_routingsav;
    private javax.swing.JTextField txt_savingtype;
    private javax.swing.JTextField txt_ssn;
    private javax.swing.JTextField txt_state;
    private javax.swing.JTextField txt_street;
    private javax.swing.JTextField txt_weight;
    private javax.swing.JTextField txt_zipcode;
    // End of variables declaration//GEN-END:variables

    private void displayDemographicDetails() {
        txt_first.setText(person.getFirstname());
        txt_last.setText(person.getLastname());
        txt_dob.setText(person.getDob());
        txt_age.setText(person.getAge());
        txt_height.setText(person.getHeight());
        txt_weight.setText(person.getWeight());
        txt_phone.setText(person.getWeight());
        txt_ssn.setText(person.getSsn());
    }

    
    private void displayCheckinBankDetails() {
        txt_banknamecheckin.setText(person.getCheckinaccount().getBnamecheck());
        txt_accnocheckin.setText(person.getCheckinaccount().getAccountnocheck());
        txt_routingcheckin.setText(person.getCheckinaccount().getRoutingnocheck());
        txt_balancecheckin.setText(person.getCheckinaccount().getBalancecheck());
        txt_checkintype.setText(person.getCheckinaccount().getAcctypecheck());
        
    }

    private void displaySavingBankDetails() {
        txt_banknamesav.setText(person.getSavingaccount().getBnamesave());
        txt_accnosav.setText(person.getSavingaccount().getAccountnosave()); 
        txt_routingsav.setText(person.getSavingaccount().getRoutingnosave());
        txt_balancesav.setText(person.getSavingaccount().getBalancesave());
        txt_savingtype.setText(person.getSavingaccount().getAcctypesave());
    }

    private void displayAddressDetails() {
        
        txt_street.setText(person.getStreet());
        txt_city.setText(person.getCity());
        txt_state.setText(person.getState());
        txt_zipcode.setText(person.getZipcode());
    }

    private void displayLicenseDetails() {
        txt_licencenum.setText(person.getLicenseno());
        txt_dtissue.setText(person.getDtofissue());
        txt_dtexpire.setText(person.getDtofexpire());
        txt_bloodtype.setText(person.getBloodtype());
    }

    private void displayMedicalRecord() {
        txt_recordno.setText(person.getRecordno());
        txt_allergy1.setText(person.getAllergy1());
        txt_allergy2.setText(person.getAllergy2());
        txt_allergy3.setText(person.getAllergy3());
    }
}
